sim_ips:             # list of Ethernet (or other fast link) IPs of the machines, the first one should be the IP of this machine
    - 192.168.1.2
    - 192.168.1.3
    - 192.168.1.4
    - 192.168.1.5
    - 192.168.1.6
      # - 192.168.1.227
oracle_port: 4096
num_obstacles: 5

# training related
ray_head_ip: 192.168.1.2:6379        # 'auto' or IP of the ray head
redis_password: "5241590000000000"   # redis password ray told you
param_server_ip: 192.168.1.2    # wireless NIC IP of the parameter server, usually you should set it to this machine
placement: spread          # 'pack' or 'spread', 'pack' for debugging on fewer machines

